
services:

  wordpress:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    restart: "no"
    volumes:
      - ./src:/var/www/html:delegated
    environment:
      - WORDPRESS_DEBUG=1

  wordpress_db:
    restart: "no"


  wordpress_cache:
    restart: "no"


