
services:
  traefik:
    image: traefik:v3.2
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--api.insecure=true"  # Only for development
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: wordpress_db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./.docker/wordpress/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./src:/var/www/html
    depends_on:
      - wordpress_db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=HostRegexp(`[a-zA-Z0-9-]+.wordpress.docker.local`) || Host(`wordpress.docker.local`)"
      - "traefik.http.routers.wordpress.entrypoints=web"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"

  wordpress_db:
    restart: always


  wordpress_cache:
    restart: always


